### ISSUE TITLE
Netty error when sending large amount of messages.

### ISSUE THREAD

**Issue by Mast3rPlan** [cloudfoundry-community/java-nats#32]
```
io.netty.handler.codec.DecoderException: ServerFrameDecoder.decode() must consume the inbound data or change its state if it did not decode anything.
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:372) ~[netty-all-4.0.6.Final.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131) ~[netty-all-4.0.6.Final.jar:na]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:333) [netty-all-4.0.6.Final.jar:na]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:319) [netty-all-4.0.6.Final.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:789) [netty-all-4.0.6.Final.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [netty-all-4.0.6.Final.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:497) [netty-all-4.0.6.Final.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:465) [netty-all-4.0.6.Final.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:359) [netty-all-4.0.6.Final.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [netty-all-4.0.6.Final.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

**Comment by mheath** [comment]
Do you have a test case that can consistently duplicate this issue?

**Comment by pires** [comment]
@Mast3rPlan which version are you using? I had the same issue just because I copied the Maven dependency from README, which points to 0.5.1.

**Comment by pires** [comment]
You can probably close this.

**Comment by mheath** [comment]
Thanks.
